export const NUM_MOVIES_PER_PAGE = 12;
export const FETCH_MOVIES_REQUESTED = 'FETCH_MOVIES_REQUESTED';
export const MOVIES_FETCHED = 'MOVIES_FETCHED';
export const ERROR_OCCURED = 'ERROR_OCCURED';
export const SET_MOVIES_PER_PAGE = 'SET_MOVIES_PER_PAGE';
export const SET_FILTERED_MOVIES = 'SET_FILTERED_MOVIES';

